[package]
name = "rust_snake"
version = "0.1.0"
authors = ["Luca <b.lucab1211@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Snake the game written in rust"
repository = "https://github.com/BrunoWallner/rust-snake"

[dependencies]
terminal_size = "0.1.16"